// Feed demo per la fase visiva. Copre le tre varianti (add_coin,
// price_alert, new_watchlist) così possiamo verificare ogni layout di card.

import type { FeedItem } from "./types";

export const FEED: FeedItem[] = [
  {
    id: "1",
    type: "add_coin",
    user: "lunavega",
    coin: "PEN",
    watchlist: "DeFi Picks",
    note: "Boost di TVL questa settimana, vale la pena tenerla d'occhio. Yield reale > 14% sui pool ETH.",
    time: "8m",
    likes: 24,
    comments: 6,
  },
  {
    id: "2",
    type: "price_alert",
    user: "matteo.eth",
    coin: "ETH",
    direction: "down",
    target: 3800,
    note: "Se rompe 3.8k apro short scalp. Stop sopra 3.9k.",
    time: "23m",
    likes: 11,
    comments: 3,
  },
  {
    id: "3",
    type: "new_watchlist",
    user: "degenale",
    watchlist: "Solana Memes",
    coins: ["WIF", "BONK", "PEPE"],
    note: "Tre memecoin che sto guardando questa settimana. Volume in crescita.",
    time: "1h",
    likes: 47,
    comments: 12,
    liked: true,
  },
  {
    id: "4",
    type: "add_coin",
    user: "sarah_btc",
    coin: "BTC",
    watchlist: "Core",
    note: "Continuo a accumulare sotto 72k. Niente di speciale, è il piano di sempre.",
    time: "2h",
    likes: 89,
    comments: 21,
  },
  {
    id: "5",
    type: "price_alert",
    user: "lunavega",
    coin: "SOL",
    direction: "up",
    target: 200,
    time: "3h",
    likes: 6,
    comments: 1,
  },
];
