-- =============================================================================
-- 0049: media_assets.variants JSONB column
-- =============================================================================
-- Holds the processed webp variants (hero/card/thumb) generated by the
-- news hero pipeline (lib/modules/news/services/hero-processor.ts).
--
-- Shape:
--   {
--     "hero":  { "url": "...", "w": 1600, "h": 1000, "size": 145320 },
--     "card":  { "url": "...", "w":  800, "h":  500, "size":  48210 },
--     "thumb": { "url": "...", "w":  400, "h":  250, "size":  14820 }
--   }
--
-- NULL for assets never used as a news hero — the column is opt-in,
-- and renderers fall back to publicUrl via pickHeroVariantUrl().
--
-- Idempotent. Paste into Supabase SQL Editor.
-- =============================================================================

ALTER TABLE "media_assets"
  ADD COLUMN IF NOT EXISTS "variants" jsonb;
